internal/gitlab/gitlab.go: Fix Jobs.Playjob call
After the package update the compile fails with

internal/gitlab/gitlab.go:1381:41: not enough arguments in call to lab.Jobs.PlayJob
	have (interface{}, int)
	want (interface{}, int, *"github.com/xanzy/go-gitlab".PlayJobOptions, ..."github.com/xanzy/go-gitlab".RequestOptionFunc)

because the Jobs.PlayJob() call now takes an additional opts struct.

Update the Validate.Lint() call by setting and passing an PlayJobOptions
struct.

Signed-off-by: Prarit Bhargava <prarit@redhat.com>